### PR TITLE
feat: Add init parameters to ABI

### LINKED ISSUE #576: ABI for init function in build output

### PR DESCRIPTION
**Pull request by rahulyadav-57**
Closes #576 

- [x] I have updated CHANGELOG.md
- [ ] ~~I have documented my contribution in Tact Docs: https://github.com/tact-lang/tact-docs/pull/PR-NUMBER~~
- [ ] ~~I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases~~
- [x] I have run all the tests locally and no test failure was reported
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

**Comment by anton-trunov** [comment]
So, here is the definition of the `ContractABI` type:

```ts
export type ContractABI = {
    name?: Maybe<string>;
    types?: Maybe<ABIType[]>;
    errors?: Maybe<{
        [key: number]: ABIError;
    }>;
    getters?: Maybe<ABIGetter[]>;
    receivers?: Maybe<ABIReceiver[]>;
};
```

The proposed solution does not conform to this type.

There is no `init` in `ContractABI`. And `init` is essentially included in each and every receiver: there is a initialization flag that is checked before executing any receiver. That said, we should either propose to extend the `ContractABI` type in `@ton/core` or go with some other solution. @Gusarich might have some more thoughts on this.

**Comment by rahulyadav-57** [comment]
@Gusarich, what is your opinion on this?

**Comment by Gusarich** [comment]
Well, Anton already explained why we can't just do what you did here.
And I personally don't see any point in adding `init` to ABI.

**Comment by rahulyadav-57** [comment]
I agree, but it might be necessary for third-party tools like Nujan, where input fields are rendered based on the initialization parameters for deployment. While I can obtain this information via the compiler context, it would be helpful for projects that do not have access to the context.

**Comment by anton-trunov** [comment]
We can provide API using a different mechanism, let's discuss this elsewhere

**Comment by anton-trunov** [comment]
@Gusarich btw, the `interfaces` property in the contract ABI object that gets returned from the `createABI` function is also non-standard

**Pull request closed without merging**
