### PR TITLE
Refactor tests

### LINKED ISSUE #346: Clean up Tact's testsuite
For instance, the grammar and typechecker tests should have suggestive names instead of case-XX.tact. The test file names should reflect the feature they test. If there is a lot of tests for one feature, we should consider grouping those into folders.

This will also help with merge conflicts, because name clashes between tests will be less likely for PRs that add different features.

### PR DESCRIPTION
**Pull request by anton-trunov**
Closes #346

- [x] I have updated CHANGELOG.md
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

**Review by novusnota — COMMENTED** [review]
Absolutely massive!

But I wonder if CLI tests are also exported in npm due to [package.json#L28](https://github.com/tact-lang/tact/blob/main/package.json#L28). Also, as of now the whole `src/` folder is included too. We may want to optimize that, although that's mostly a nitpick.

Description of [`files` field in package.json](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#files)

image

**Comment by Gusarich** [comment]
This is an amazing improvement to the codebase! The tests were a big and not very structured mess that was only getting worse. Now it'll be easier to contribute and resolve merge conflicts in PRs!

**Review by Gusarich — COMMENTED** [review]
What if we also remove the `feature-` prefix from `.spec.ts` files in e2e tests?

**Comment by anton-trunov** [comment]
> But I wonder if CLI tests are also exported in npm due to [package.json#L28](https://github.com/tact-lang/tact/blob/main/package.json#L28).

good point! fixed

> Also, as of now the whole src/ folder is included too. We may want to optimize that, although that's mostly a nitpick.

@novusnota can you please open a new issue about it? we should follow the best practices for npm packaging

> What if we also remove the feature- prefix from .spec.ts files in e2e tests?

@Gusarich good point as well! done

**Review by Gusarich — APPROVED** [review]

**Pull request merged**
