### PR TITLE
chore: update gh actions to node 20

### LINKED ISSUE #320: Upgrade Node.js actions
Here is what GitHub Actions reports:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### PR DESCRIPTION
**Pull request by vitorpy**
Closes #320

- [X] I have updated CHANGELOG.md
- [X] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [X] I have run all the tests locally and no test failure was reported
- [X] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

**Comment by novusnota** [comment]
We could also add the `"packageManager": "yarn@1.22.22"` field to `package.json` now: https://github.com/tact-lang/tact/issues/320#issuecomment-2092904574

**Comment by anton-trunov** [comment]
@vitorpy do you think this PR is ready?

**Comment by vitorpy** [comment]
> @vitorpy do you think this PR is ready?

CHANGELOG updated, ready for review.

**Review by anton-trunov — APPROVED** [review]
Thanks!

**Pull request merged**
