### PR TITLE
Check if the input of `ton` global function is a valid number

### PR DESCRIPTION
**Pull request by mhbdev**
This checked will solve the problem faced in  #113

### CODE REVIEW

**Comment by Gusarich** [comment]
I don't think it's necessary. If the number isn't valid, it throws an error during compilation which tells what exactly is wrong.

**Comment by mhbdev** [comment]
> I don't think it's necessary. If the number isn't valid, it throws an error during compilation which tells what exactly is wrong.

You are right.
I have made another change hope you guys find it useful.

**Comment by Gusarich** [comment]
@mhbdev can you please explain what this change does?

**Comment by mhbdev** [comment]
> @mhbdev can you please explain what this change does?

I decided to make this change to let the input contain separators like comma and underscore. So there would be no error using those separators to make your numbers more readable.

**Comment by Gusarich** [comment]
> I decided to make this change to let the input contain separators like comma and underscore. So there would be no error using those separators to make your numbers more readable.

I'm not sure if it's correct to do that for in string literals. This needs clarification from @anton-trunov

**Comment by anton-trunov** [comment]
Hey @mhbdev, thanks for the PR, however, I'm inclined to close it because it allows a bit too much freedom, like several commas in a row or leading or trailing commas, which would arguably allow for even less readable code. Hope this won't discourage you from future contribution.

**Pull request closed without merging**
