### PR TITLE
fix: load address opt (#370)

### LINKED ISSUE #370: Tact generates incorrect `__tact_load_address_opt`
When defining
```
message MsgA {
    x: Int as uint8;
    y: Address?;
    z: Int as uint16;
}
```

Tact generates the following code in *.stdlib.fc

```
(slice, slice) __tact_load_address_opt(slice cs) inline {
    slice raw = cs~load_msg_addr();
    if (raw.preload_uint(2) != 0) {
        return (cs, __tact_verify_address(raw));
    } else {
        return (cs, null());
    }
}
```
It should skip 2 bits in the else branch before returning.

### PR DESCRIPTION
**Pull request by 0kenx**
Closes #370

- [x] I have updated CHANGELOG.md
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

**Comment by anton-trunov** [comment]
Thanks a bunch for helping by contributing a fix! Really appreciate it. Could you please resolve the merge conflicts? Looks like your PR is based on an outdated version of the main branch

**Comment by 0kenx** [comment]
Merged main

**Review by anton-trunov — DISMISSED** [review]

**Comment by anton-trunov** [comment]
Hey @0kenx, your contribution qualifies for the Tact contributor [SBT](https://society.ton.org/contribute-to-tact-compiler), would you mind sharing your TON wallet?

**Comment by anton-trunov** [comment]
@0kenx CI is failing. You need to update some of the test snapshots, I tried pushing a fix to your branch but I don't have access. So I pushed it to the Tact repo: https://github.com/tact-lang/tact/commit/ae6f1df14a39f552437e9a56a41905bedad2e37a.

To do it on your side, you can use the following commands:

```shell
yarn gen && yarn build && yarn test -u
```

**Comment by 0kenx** [comment]
CI fails for some snapshot tests, which I believe are expecting some particular FunC code to be generated, and since my code changed FunC code generation, those tests fail.

**Comment by 0kenx** [comment]
It's now merged and all tests and lints pass on local.

**Comment by 0kenx** [comment]
> Hey @0kenx, your contribution qualifies for the Tact contributor [SBT](https://society.ton.org/contribute-to-tact-compiler), would you mind sharing your TON wallet?

UQCbfeyLatuHjLHkuToQEoF37M9TU-RvQk-XSr9eu75vWteC

**Review by anton-trunov — APPROVED** [review]

**Comment by anton-trunov** [comment]
Thanks a lot! SBT sent

**Pull request merged**
