### PR TITLE
feat: add `VarInt16`, `VarInt32`, `VarUint16`, `VarUint32` Integer Formats and fix `coins` in `foreach`

### LINKED ISSUE #1117: `VarUInt32`, `VarInt16`, `VarInt32` serialization types
Currently only `VarUInt16` is supported as `coins`, but some cases require other variations of variable-sized integers, like `VarUInt32` for extra currency operations. Actually, it'd be good to also add `VarInt16` and `VarInt32` to have all the available types implemented (TVM only has instructions for 16 and 32). Also we should probably support `VarUInt16` as another name for `coins` to support backwards compatibility.

Related issue: #986

### LINKED ISSUE #1214: `foreach` does not work correctly for `Int as coins` value serialization
The function below compiles successfully but throws `9` exit code in runtime.

```tact
fun f(): Int {
    let m: map<Int, Int as coins> = emptyMap();
    m.set(1, 100);
    m.set(2, 200);

    let sum: Int = 0;
    foreach (k, v in m) {
        sum += k + v;
    }

    return sum;
}
```

This is due to the fact that there is no `coins` serialization handling in foreach codegen:
 - https://github.com/tact-lang/tact/blob/91569213d6f0faace7747a60a3bb7754e40cc083/src/generator/writers/writeFunction.ts#L287-L295
 -  https://github.com/tact-lang/tact/blob/91569213d6f0faace7747a60a3bb7754e40cc083/src/generator/writers/writeFunction.ts#L375-L383

### PR DESCRIPTION
**Pull request by Gusarich**
## Issue

Closes #1117 and closes #1214.

## Checklist

- [x] I have updated CHANGELOG.md
- [ ] I have documented my contribution in `docs/` and made the build locally
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

**Comment by Gusarich** [comment]
@anton-trunov `maps.tact` fails during FunC compilation after adding new value formats... we have exceeded the 255 usable stack items limit

`fatal: Too deep stack`

**Comment by anton-trunov** [comment]
there is a merge conflict: src/types/__snapshots__/resolveDescriptors.spec.ts.snap

**Comment by Gusarich** [comment]
Discovered #1214 while implementing varints support for `foreach`, fixed that in the same commit

**Comment by Gusarich** [comment]
also depends on https://github.com/ton-org/ton-core/pull/59

**Comment by novusnota** [comment]
I'll write the docs for this soon

**Review by anton-trunov — APPROVED** [review]
Merging this without the corresponding doc section because it's a blocker on FunC 0.4.6 update

**Pull request merged**
