### PR TITLE
feat: optional trailing semicolons for struct/message field declarations

### LINKED ISSUE #393: Make semicolon (`;`) optional for the last struct field declaration
The following should be allowed:

```tact
struct Foo { a: Int }
```

or

```tact
struct Bar { a: Int; b: String }
```

(currently one has to add `;` after each struct field declaration)

### PR DESCRIPTION
**Pull request by anton-trunov**
Closes #393

- [x] I have updated CHANGELOG.md
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

**Review by novusnota — COMMENTED** [review]
What's the motivation behind the separate `StructFields` and not an inline `ListOf<StructField, ";"> ";"`? Other parts of the grammar prefer the latter :)

**Comment by Gusarich** [comment]
Agree with @novusnota

**Comment by anton-trunov** [comment]
> What's the motivation behind the separate StructFields and not an inline ListOf<StructField, ";"> ";"? 

To reduce duplication

**Comment by anton-trunov** [comment]
We can actually do the same for the other parts too. But in separate PRs

**Comment by anton-trunov** [comment]
I'm going to merge this and postpone some grammar refactoring to a later PR, this is tracked in #397

**Pull request merged**
