### PR TITLE
Fix typo in 10 Commandments of Tact documentation

### PR DESCRIPTION
**Pull request by cemorum**
The text provided is already quite comprehensive and well-written. However, there is a minor typo in the "10 Commandments of Tact" section, specifically in point 3. The word "lets" should be corrected to "lets you." Here's the improved line:

Original:
"Tact offers strong compile-time checks for contract interfaces, typed addresses and lets describe messages natively in a subset of TL-B."

Improved:
"Tact offers strong compile-time checks for contract interfaces, typed addresses and lets you describe messages natively in a subset of TL-B."

### CODE REVIEW

**Comment by anton-trunov** [comment]
@cemorum thanks for you effort, but could you please not ignore our PR template?

**Comment by anton-trunov** [comment]
you need to open an issue, link it in the PR and also please refrain from introducing unrelated changes like the ones in the wallet.spec.ts file

**Comment by cemorum** [comment]
Hi anton, its my first time contributing to the repo. Can you please tell
me how can i link the PR with an issue?

ср, 26 июн. 2024 г. в 13:11, Anton Trunov ***@***.***>:

**Comment by anton-trunov** [comment]
when you opened a PR you saw the template, you can copy it from https://raw.githubusercontent.com/tact-lang/tact/main/.github/pull_request_template.md and edit your original post filling in the blanks

**Comment by anton-trunov** [comment]
also, you have merge conflicts in the README.md file

**Pull request closed without merging**
