### PR TITLE
fix: verify address for non-zero workchains

### LINKED ISSUE #369: Tact generated FunC code is not future proof
Why does Tact generate the following FunC code:
```
slice __tact_verify_address(slice address) inline {
    throw_unless(136, address.slice_bits() == 267);
    var h = address.preload_uint(11);
    throw_if(137, h == 1279);
    throw_unless(136, h == 1024);
    return address;
}
```
Wouldn't that always fail when `chain ID != 0` when in the future some addresses are from a different chain ID?

It should just generate
```
-    throw_unless(136, h == 1024);
+    throw_unless(136, h >> 8 == 2);
````

### PR DESCRIPTION
**Pull request by 0kenx**
Closes #369

- [x] I have updated CHANGELOG.md
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

**Comment by anton-trunov** [comment]
Looks like there are some merge conflicts now

**Comment by 0kenx** [comment]
```
-------------------------------------------
Issues found:
./CHANGELOG.md:21:65 - Unknown word (workchains)
./examples/__snapshots__/wallet.spec.ts.snap:20:38 - Unknown word (Tfre)
./examples/__snapshots__/wallet.spec.ts.snap:20:48 - Unknown word (Eikcyp)
./examples/__snapshots__/wallet.spec.ts.snap:20:58 - Unknown word (umrg)
./examples/__snapshots__/wallet.spec.ts.snap:48:38 - Unknown word (Tfre)
./examples/__snapshots__/wallet.spec.ts.snap:48:48 - Unknown word (Eikcyp)
./examples/__snapshots__/wallet.spec.ts.snap:48:58 - Unknown word (umrg)
./examples/__snapshots__/wallet.spec.ts.snap:65:42 - Unknown word (Tfre)
./examples/__snapshots__/wallet.spec.ts.snap:65:52 - Unknown word (Eikcyp)
./examples/__snapshots__/wallet.spec.ts.snap:65:62 - Unknown word (umrg)
./examples/__snapshots__/wallet.spec.ts.snap:95:38 - Unknown word (Tfre)
./examples/__snapshots__/wallet.spec.ts.snap:95:48 - Unknown word (Eikcyp)
./examples/__snapshots__/wallet.spec.ts.snap:95:58 - Unknown word (umrg)
./examples/__snapshots__/wallet.spec.ts.snap:126:38 - Unknown word (Tfre)
./examples/__snapshots__/wallet.spec.ts.snap:126:48 - Unknown word (Eikcyp)
./examples/__snapshots__/wallet.spec.ts.snap:126:58 - Unknown word (umrg)
./src/test/__snapshots__/feature-send.spec.ts.snap:21:33 - Unknown word (Ybxdypbqpxk)
./src/test/__snapshots__/feature-send.spec.ts.snap:21:55 - Unknown word (XBBPHS)
./src/test/__snapshots__/feature-send.spec.ts.snap:39:35 - Unknown word (Ybxdypbqpxk)
./src/test/__snapshots__/feature-send.spec.ts.snap:39:57 - Unknown word (XBBPHS)
./src/test/__snapshots__/feature-send.spec.ts.snap:70:33 - Unknown word (Ybxdypbqpxk)
./src/test/__snapshots__/feature-send.spec.ts.snap:70:55 - Unknown word (XBBPHS)
./src/test/__snapshots__/feature-send.spec.ts.snap:115:33 - Unknown word (Ybxdypbqpxk)
./src/test/__snapshots__/feature-send.spec.ts.snap:115:55 - Unknown word (XBBPHS)
./src/test/__snapshots__/feature-send.spec.ts.snap:133:37 - Unknown word (Ybxdypbqpxk)
./src/test/__snapshots__/feature-send.spec.ts.snap:133:59 - Unknown word (XBBPHS)
CSpell: Files checked: 443, Issues found: 26 in 3 files.
```

**Comment by anton-trunov** [comment]
I would add to the [list of ignored files](https://github.com/tact-lang/tact/blob/main/cspell.json#L64):
- `src/test/__snapshots__/feature-send.spec.ts.snap`
- `examples/__snapshots__/wallet.spec.ts.snap`

and `workchains` to the vocabulary: https://github.com/tact-lang/tact/blob/main/cspell.json#L57

**Comment by 0kenx** [comment]
`tact-template` also has a snapshot test...

**Comment by Gusarich** [comment]
Forbidding other workchains is OK and it’s done in many common smart contracts.

However, we can introduce another configuration parameter for it, similar to the one that allows masterchain messages.

**Comment by anton-trunov** [comment]
As @Gusarich mentioned above and added a bit more elsewhere:

> it's still unclear how will completely different workchains (for example, with different VMs) communicate, so it's better to just forbid access from other workchains and it's done in many network-wide contracts such as tokens

This means this PR indeed needs to introduce a config flag as again mentioned by Daniil before. This will put the burden of making this decision on the user. And it will solve the problem with tact-template as well.

**Pull request closed without merging**
